# Generated by Django 4.0.1 on 2022-01-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopcars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['car_relase_date'], 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AddField(
            model_name='cars',
            name='car_price',
            field=models.CharField(max_length=100, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='cars',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_brand',
            field=models.CharField(max_length=200, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_desription',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cars',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shopcars.category', verbose_name='Категория'),
        ),
    ]
